# Generated by Django 2.0 on 2019-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190510_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='uploads/article/2019/05/10/photos2.jpg', upload_to='uploads/article/%Y/%m/%d', verbose_name='文章图片'),
        ),
    ]
